docker:
    - as_root: true
    - image: juja/rultor-juja-microservices
install:
    - cd simple-slack-api/
    - gradle clean install
    - cd ../
architect:
    - vkuchyn
merge:
  script:
    - mvn clean install -Pqulice --errors